### ISSUE TITLE
Multiconfig

### ISSUE THREAD

**Issue by 1cec0ld** [ModDamage/ModDamage#227]
# MultiConfig
- Allow loading individual local scripts in a single folder
- Can enable and disable individual scripts
- And more...
## Tasks

Note some of these tasks are completed just may need refining before considered completed.
- [ ] Throw config instances through methods
- [ ] Seperate main config from scripts
- [x] ScriptManager
  - [x] Script scanner (Scans directories recursively for scripts
  - [x] Script loader (Loads scripts)
  - [x] Script management (Fetch scripts by name and more)
- [ ] Complete this task list!
