### ISSUE TITLE
Documentation within the web server

### ISSUE THREAD

**Issue by ErichDonGubler** [ModDamage/ModDamage#238]
Koryu[Mibbit]   User story: I plopped in ModDamage, all I know is that the webserver's supposed to help me. 
20:50   Koryu[Mibbit]   Goes to web server.
20:50   Koryu[Mibbit]   Sees complete examples for everything he gets interested in clicking on.
20:51   Koryu[Mibbit]    Instead of "Frick, don't understand this" and having to go to another wiki site to learn.
## Tasks
- [ ] Annotation @Doc
- [ ] Conditionals Marked with @Doc
- [ ] Routines Marked with @Doc
- [ ] Properties Marked with @Doc
- [ ] Missing any more tasks?
