### ISSUE TITLE
Location Tags not saved correctly

### ISSUE THREAD

**Issue by coaster3000** [ModDamage/ModDamage#256]
Users reported a long standing bug with persistent location tags.

Upon testing the data is saved but never loaded due to some issues in current code.
# Issues
- Data is not loaded from locations
- Data is not being saved in the correct format _OR_ not being loaded in the format it is currently using.
# Tasks
- [x] Find best method for fetching the location data.
- [x] Store data and load data in the _SAME_ format.
  - [x] Setup a parsing system for loading string data instead. <sup>If above task fails </sup>
